### ISSUE TITLE
Testing - fails to read file

### ISSUE THREAD

**Issue by JPL1** [josephm1/safe-demo#1]
Hi - not so sure how deep to go into this cos I realise it's very much a work in progress, but when I try to get or create a NFS file I get a failure logged by the launcher. I then find that I need to authenticate again. However, when I click again on Home - the Launcher logs that a file has been created successfully.

Using Windows 10 + AMPPS web server + Safe Browser + Launcher with mock routing 

![safe-web-app-demo](https://cloud.githubusercontent.com/assets/12783198/25594909/88d40080-2eba-11e7-98e9-15b9e23f4d7b.png)

**Comment by josephm1** [comment]
Github wasn't letting me comment for some awhile
To get it up and running on the chrome you can use this [webserver ](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en1)
and [this ](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en1) to enable cors
you will also need the safe launcher with mock routing running 
also the file path means you are giving the file a name on the safe network so to do anything on the nfs file you need to enter something in  filepath

**Comment by JPL1** [comment]
That link about enabling CORS is broken. I have tried ticking and unticking the Set CORS Headers box and restarted the plugin each time, but no joy. It won't authenticate. Win 10, Launcher 11 with mock routing, Chrome browser.

![safe-web-demo-app-auth-error](https://cloud.githubusercontent.com/assets/12783198/25780572/6e9a1068-3321-11e7-8285-45ab7b91947f.png)

**Comment by josephm1** [comment]
ccould you try this plugin instead https://chrome.google.com/webstore/detail/cors-toggle/omcncfnpmcabckcddookmnajignpffnh?hl=en1

**Comment by JPL1** [comment]
Fixes the CORS issue but I still get this error on trying to authenticate
Fetch API cannot load http://localhost:8100/0.5/auth. Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
authsafe.js:47 TypeError: Failed to fetch

**Comment by josephm1** [comment]
Go into the options of the cors extension and add "Content-Type"

**Comment by josephm1** [comment]
Try this plugin instead

**Comment by josephm1** [comment]
Try this plugin https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en1

**Comment by JPL1** [comment]
That worked
